### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by wwahammy** [dhmncivichacks/isitrecyclingweek-android#27]
When you go to the homescreen of itrecyclingweek and press the back button, the isitrecyclingweek screen reloads instead of going to the previous screen, in my case the phone homescreen.

**Comment by mikeputnam** [comment]
Thanks for using the app! Sorry it misbehaved on you.

Was this the flow to reproduce the bug?:
- Open app for the first time
- Set location
- Arrive at home screen of the recycling app
- Press "back" triangle
- _Expected_: Phone home screen _Actual_: back on recycling app home screen

I was unable to reproduce the problem using those steps.  Do you know if there were other steps in triggering the bug that I missed?

**Comment by wwahammy** [comment]
I attempted to set the location but my location wasn't found (probably
because I'm not in the city of Appleton). So it stays at the location
screen and when I press back, it just reloads the location screen.

**Comment by mikeputnam** [comment]
Ah! I see.  I neglected to sufficiently test the address-not-found scenario.

Thanks for pointing that out.  I'll fix that with the next version.
