### ISSUE TITLE
Re-name this repo to isitrecyclingweek-android

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/isitrecyclingweek-android#32]
Follow the naming pattern established by https://github.com/dhmncivichacks/isitrecyclingweek-web

**Comment by mikeputnam** [comment]
Done.

**Comment by bobwaldron** [comment]
you must be getting ready to refactor to v.2.0   :)

**Comment by mikeputnam** [comment]
Getting a new phone and installing the Is It Recycling Week? app reminded me to go look at usage stats. We're at 24 users currently. Then I recalled that I still hadn't finished incorporating the work the @mrosack had done to make the data usable/available in all the participating municipalities; into the Android app. This shall not stand!

**Comment by bobwaldron** [comment]
woo hoo!!  Nexus 5X ftw!

so are you a Poke Mongoloid? (Luke came up with that...)

http://www.newyorker.com/tech/elements/pokemon-go-will-make-you-crave-augmented-reality

need to do an AR overlay on the garbage dumpsters/cans, gamify IIRW...
