### ISSUE TITLE
Do v2.0.0 release

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/isitrecyclingweek-android#40]
TODO:
- [x] Update "About" attribution
- [x] Play store "About" attribution
- [x] Screenshots for README and Play store
- [x] Summarize changes for Play store and Github release notes
- [x] No longer Appleton specific
- [x] Clean up dead code post-refactor

Test:
- [x] Negative tests
- [x] Failure scenarios
- [x] Multiple Android versions and devices

Create release and build final v2.0.0 apk
- [x] bump version numbers in build.gradle

**Comment by bobwaldron** [comment]
Yay, cool to see v2.0.0 in cyber-print!

Bob
